# Generated by Django 5.2.1 on 2025-05-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_is_active_customuser_is_staff'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='low_stock_threshold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='business_type',
            field=models.CharField(blank=True, choices=[('Sole proprietorship', 'Sole proprietorship'), ('General partnership', 'General partnership'), ('Limited partnership', 'Limited partnership'), ('Limited liability partnership (LLP)', 'Limited liability partnership (LLP)'), ('C corporation', 'C corporation'), ('S corporation', 'S corporation'), ('Benefit corporation', 'Benefit corporation'), ('Limited liability company (LLC)', 'Limited liability company (LLC)'), ('Nonprofit', 'Nonprofit'), ('Joint venture', 'Joint venture')], max_length=150),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(condition=models.Q(('low_stock_threshold__gte', 0)), name='low_stock_threshold_gte_0'),
        ),
    ]
