# Generated by Django 5.2.1 on 2025-06-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_low_stock_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='default_order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rcv_mail_for_low_stocks',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rcv_mail_for_new_orders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rcv_mail_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rcv_msg_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='low_stock_threshold',
            field=models.IntegerField(default=5),
        ),
    ]
