# Generated by Django 5.2.1 on 2025-06-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_default_order_status_customuser_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='business_address',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='customuser',
            name='business_phone',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='business_email',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
