# Generated by Django 5.2.1 on 2025-07-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_email_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='passwd_reset_otp_with_time_created',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
