# Generated by Django 5.2.1 on 2025-06-04 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('client_email', models.CharField(blank=True, max_length=150)),
                ('client_phone', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered')], null=True)),
                ('order_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_ordered', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('cummulative_price', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('order_id', 'product_ordered'), name='unique_product_in_order')],
            },
        ),
    ]
