# Generated by Django 5.2.1 on 2025-06-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orderedproduct',
            name='unique_product_in_order',
        ),
        migrations.RenameField(
            model_name='orderedproduct',
            old_name='product_ordered',
            new_name='name',
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='orderedproduct',
            constraint=models.UniqueConstraint(fields=('order_id', 'name'), name='unique_product_in_order'),
        ),
    ]
