# Generated by Django 5.2.1 on 2025-06-08 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orderedproduct_owner_id_order_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='owner_id',
            new_name='product_owner_id',
        ),
    ]
