# Generated by Django 5.2.1 on 2025-06-26 03:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_total_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total_price__gt', 0)), name='total_price_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='orderedproduct',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='order_price_greater_than_zero'),
        ),
    ]
