# Generated by Django 5.2.1 on 2025-06-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_total_price_gt_zero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='cummulative_price',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AddConstraint(
            model_name='orderedproduct',
            constraint=models.CheckConstraint(condition=models.Q(('cummulative_price__gt', 0)), name='cummulative_price_greater_than_zero'),
        ),
    ]
