# Generated by Django 5.2.1 on 2025-07-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_status_alter_order_total_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderedproduct',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(),
        ),
    ]
