# Generated by Django 5.2.1 on 2025-06-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='low_stock_threshold',
            field=models.IntegerField(default=0),
        ),
    ]
