# Generated by Django 5.2.1 on 2025-06-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_low_stock_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='low_stock_threshold',
            field=models.IntegerField(default=5),
        ),
    ]
