# Generated by Django 5.2.1 on 2025-06-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_low_stock_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='product_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
