# Generated by Django 5.2.1 on 2025-06-24 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventory_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
