# Generated by Django 5.2.1 on 2025-07-15 22:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventory_price_greater_than_zero'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
