# Generated by Django 5.2.1 on 2025-07-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_inventory_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='date_added',
            field=models.DateField(),
        ),
    ]
